[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/posts/learned-about-web-industry/"
  to = "/posts/2017/learned-about-web-industry/"
